---
abstract: 'Module to interface with the ORCID webservice'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0.31
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-ORCID
provides:
  WWW::ORCID:
    file: lib/WWW/ORCID.pm
    version: 0.01
  WWW::ORCID::API:
    file: lib/WWW/ORCID/API.pm
    version: 0
  WWW::ORCID::API::Common:
    file: lib/WWW/ORCID/API/Common.pm
    version: 0
  WWW::ORCID::API::Pub:
    file: lib/WWW/ORCID/API/Pub.pm
    version: 0
  WWW::ORCID::Transport:
    file: lib/WWW/ORCID/Transport.pm
    version: 0
  WWW::ORCID::Transport::HTTP::Tiny:
    file: lib/WWW/ORCID/Transport/HTTP/Tiny.pm
    version: 0
  WWW::ORCID::Transport::LWP:
    file: lib/WWW/ORCID/Transport/LWP.pm
    version: 0
recommends:
  JSON::XS: 2.3
requires:
  JSON: 2.51
  LWP::UserAgent: 0
  Moo: 1.000008
  URI: 0
  XML::Writer: 0
  namespace::clean: 0.24
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
